### ISSUE TITLE
DTOs

### ISSUE THREAD

**Issue by aleixmorgadas** [aleixmorgadas/nem-library#1]
- [x] AccountHistoricalDataViewModel
- [x] AccountImportanceViewModel
- [x] AccountInfo
- [x] AccountMetaData
- [x] AccountMetaDataPair
- [x] AccountPrivateKeyTransactionsPage
- [x] ApplicationMetaData
- [x] AuditCollection
- [x] Block
- [x] BlockChainScore
- [x] BlockHeight
- [x] BootNodeRequest
- [x] CommunicationTimeStamps
- [x] ExplorerBlockViewModel
- [x] ExplorerTransferViewModel
- [x] ExtendedNodeExperiencePair
- [x] HarvestInfo
- [x] KeyPairViewModel
- [x] ImportanceTransferTransaction
- [x] MosaicDefinitionCreationTransaction
- [x] MosaicSupplyChangeTransaction
- [x] MultisigAggregateModificationTransaction
- [x] MultisigCosignatoryModification
- [x] MultisigSignatureTransaction
- [x] MultisigTransaction
- [x] ProvisionNamespaceTransaction
- [x] TransferTransaction
- [x] Mosaic
- [x] MosaicDefinition
- [x] MosaicDefinitionMetaDataPair
- [x] MosaicProperties
- [x] MosaicLevy
- [x] MosaicId
- [x] Namespace
- [x] NamespaceMetaDataPair
- [x] NemAnnounceResult
- [x] NemAsyncTimerVisitor
- [x] NemRequestResult
- [x] NisNodeInfo
- [x] Node
- [x] NodeCollection
- [x] PrivateKey
- [x] RequestAnnounce
- [x] RequestPrepareAnnounce
- [x] TimeSynchronizationResult
- [x] TransactionMetaData
- [x] TransactionMetaDataPair
- [x] UnconfirmedTransactionMetaData
- [x] UnconfirmedTransactionMetaDataPair
- [x] Error object

**Comment by guillemsole** [comment]
Created all DTOs interfaces

**Comment by aleixmorgadas** [comment]
I have moved SignedTransaction to model folder
