### ISSUE TITLE
NodeHttp

### ISSUE THREAD

**Issue by aleixmorgadas** [aleixmorgadas/nem-library#4]
Map http endpoint

Requesting information about a node
- [x] Basic node information
- [x] Extended node information

Request for discovering the neighborhood of a node
- [x] Complete neighborhood
- [x] Reachable neighborhood
- [x] Active neighborhood
- [x] Maximum chain height in the active neighborhood

- [x] Requesting node experiences
- [x] Booting the local node

- [x] Models

**Comment by guillemsole** [comment]
What shall we do with the endpoints pointing to local NIS instances like "Booting the local node"? I would implement it but would be difficult to test.

**Comment by aleixmorgadas** [comment]
In this case, we just do e2e testing manually until we find a better way to test it.
